from ._gaussian_mixture_model import gaussian_mixture_model
from ._k_means_clustering import k_means_clustering
from ._affinity_propagation import affinity_propagation
from ._spectral_clustering import spectral_clustering
from ._mean_shift import mean_shift
from ._clustering_dock_widget import attach_clustering_dock_widget